services:
  - type: web
    name: portfolio-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "your-app.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://your-app.onrender.com"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        value: "your-email@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "your-app-password"

databases:
  - name: portfolio-db
    plan: free
