# Generated by Django 4.2.7 on 2025-09-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
